// ユメタン1 単語データ - 1000語データベース
// 語順は番号1〜1000で管理され、範囲指定で学習可能
const vocabularyData = [
    // Words 1-50
    { id: 1, english: "ability", japanese: "能力", pronunciation: "əˈbɪləti" },
    { id: 2, english: "accept", japanese: "受け入れる", pronunciation: "ækˈsept" },
    { id: 3, english: "access", japanese: "接近、アクセス", pronunciation: "ˈækses" },
    { id: 4, english: "account", japanese: "口座、説明", pronunciation: "əˈkaʊnt" },
    { id: 5, english: "action", japanese: "行動", pronunciation: "ˈækʃən" },
    { id: 6, english: "active", japanese: "活動的な", pronunciation: "ˈæktɪv" },
    { id: 7, english: "activity", japanese: "活動", pronunciation: "ækˈtɪvəti" },
    { id: 8, english: "actual", japanese: "実際の", pronunciation: "ˈæktʃuəl" },
    { id: 9, english: "address", japanese: "住所、演説", pronunciation: "əˈdres" },
    { id: 10, english: "adult", japanese: "大人", pronunciation: "ˈædʌlt" },
    { id: 11, english: "advance", japanese: "進歩、前進", pronunciation: "ədˈvæns" },
    { id: 12, english: "advantage", japanese: "有利", pronunciation: "ədˈvæntɪdʒ" },
    { id: 13, english: "advice", japanese: "助言", pronunciation: "ədˈvaɪs" },
    { id: 14, english: "affect", japanese: "影響する", pronunciation: "əˈfekt" },
    { id: 15, english: "afford", japanese: "余裕がある", pronunciation: "əˈfɔrd" },
    { id: 16, english: "afraid", japanese: "恐れて", pronunciation: "əˈfreɪd" },
    { id: 17, english: "agency", japanese: "機関", pronunciation: "ˈeɪdʒənsi" },
    { id: 18, english: "agent", japanese: "代理人", pronunciation: "ˈeɪdʒənt" },
    { id: 19, english: "agree", japanese: "同意する", pronunciation: "əˈgri" },
    { id: 20, english: "agreement", japanese: "合意", pronunciation: "əˈgrimənt" },
    { id: 21, english: "ahead", japanese: "前方に", pronunciation: "əˈhed" },
    { id: 22, english: "allow", japanese: "許可する", pronunciation: "əˈlaʊ" },
    { id: 23, english: "alone", japanese: "一人で", pronunciation: "əˈloʊn" },
    { id: 24, english: "already", japanese: "すでに", pronunciation: "ɔlˈredi" },
    { id: 25, english: "although", japanese: "〜だけれども", pronunciation: "ɔlˈðoʊ" },
    { id: 26, english: "amazing", japanese: "驚くべき", pronunciation: "əˈmeɪzɪŋ" },
    { id: 27, english: "among", japanese: "〜の間に", pronunciation: "əˈmʌŋ" },
    { id: 28, english: "amount", japanese: "量", pronunciation: "əˈmaʊnt" },
    { id: 29, english: "analysis", japanese: "分析", pronunciation: "əˈnæləsɪs" },
    { id: 30, english: "ancient", japanese: "古代の", pronunciation: "ˈeɪnʃənt" },
    { id: 31, english: "animal", japanese: "動物", pronunciation: "ˈænəməl" },
    { id: 32, english: "announce", japanese: "発表する", pronunciation: "əˈnaʊns" },
    { id: 33, english: "answer", japanese: "答える", pronunciation: "ˈænsər" },
    { id: 34, english: "appear", japanese: "現れる", pronunciation: "əˈpɪr" },
    { id: 35, english: "approach", japanese: "接近する", pronunciation: "əˈproʊtʃ" },
    { id: 36, english: "area", japanese: "地域", pronunciation: "ˈeriə" },
    { id: 37, english: "argue", japanese: "議論する", pronunciation: "ˈɑrgju" },
    { id: 38, english: "argument", japanese: "議論", pronunciation: "ˈɑrgjumənt" },
    { id: 39, english: "arrive", japanese: "到着する", pronunciation: "əˈraɪv" },
    { id: 40, english: "article", japanese: "記事", pronunciation: "ˈɑrtɪkəl" },
    { id: 41, english: "artist", japanese: "芸術家", pronunciation: "ˈɑrtɪst" },
    { id: 42, english: "assume", japanese: "仮定する", pronunciation: "əˈsum" },
    { id: 43, english: "attack", japanese: "攻撃する", pronunciation: "əˈtæk" },
    { id: 44, english: "attempt", japanese: "試みる", pronunciation: "əˈtempt" },
    { id: 45, english: "attend", japanese: "出席する", pronunciation: "əˈtend" },
    { id: 46, english: "attention", japanese: "注意", pronunciation: "əˈtenʃən" },
    { id: 47, english: "attitude", japanese: "態度", pronunciation: "ˈætɪtud" },
    { id: 48, english: "attract", japanese: "引きつける", pronunciation: "əˈtrækt" },
    { id: 49, english: "author", japanese: "著者", pronunciation: "ˈɔθər" },
    { id: 50, english: "available", japanese: "利用できる", pronunciation: "əˈveɪləbəl" },
    
    // Words 51-100
    { id: 51, english: "average", japanese: "平均", pronunciation: "ˈævərɪdʒ" },
    { id: 52, english: "avoid", japanese: "避ける", pronunciation: "əˈvɔɪd" },
    { id: 53, english: "award", japanese: "賞", pronunciation: "əˈwɔrd" },
    { id: 54, english: "aware", japanese: "気づいている", pronunciation: "əˈwer" },
    { id: 55, english: "background", japanese: "背景", pronunciation: "ˈbækgraʊnd" },
    { id: 56, english: "balance", japanese: "バランス", pronunciation: "ˈbæləns" },
    { id: 57, english: "basic", japanese: "基本的な", pronunciation: "ˈbeɪsɪk" },
    { id: 58, english: "battle", japanese: "戦い", pronunciation: "ˈbætəl" },
    { id: 59, english: "beautiful", japanese: "美しい", pronunciation: "ˈbjutəfəl" },
    { id: 60, english: "become", japanese: "なる", pronunciation: "bɪˈkʌm" },
    { id: 61, english: "behavior", japanese: "行動", pronunciation: "bɪˈheɪvjər" },
    { id: 62, english: "belief", japanese: "信念", pronunciation: "bɪˈlif" },
    { id: 63, english: "believe", japanese: "信じる", pronunciation: "bɪˈliv" },
    { id: 64, english: "benefit", japanese: "利益", pronunciation: "ˈbenəfɪt" },
    { id: 65, english: "beyond", japanese: "〜を越えて", pronunciation: "bɪˈjɑnd" },
    { id: 66, english: "billion", japanese: "10億", pronunciation: "ˈbɪljən" },
    { id: 67, english: "border", japanese: "国境", pronunciation: "ˈbɔrdər" },
    { id: 68, english: "breath", japanese: "息", pronunciation: "breθ" },
    { id: 69, english: "bridge", japanese: "橋", pronunciation: "brɪdʒ" },
    { id: 70, english: "brief", japanese: "短い", pronunciation: "brif" },
    { id: 71, english: "bright", japanese: "明るい", pronunciation: "braɪt" },
    { id: 72, english: "broad", japanese: "広い", pronunciation: "brɔd" },
    { id: 73, english: "broken", japanese: "壊れた", pronunciation: "ˈbroʊkən" },
    { id: 74, english: "budget", japanese: "予算", pronunciation: "ˈbʌdʒɪt" },
    { id: 75, english: "build", japanese: "建てる", pronunciation: "bɪld" },
    { id: 76, english: "business", japanese: "ビジネス", pronunciation: "ˈbɪznəs" },
    { id: 77, english: "button", japanese: "ボタン", pronunciation: "ˈbʌtən" },
    { id: 78, english: "camera", japanese: "カメラ", pronunciation: "ˈkæmərə" },
    { id: 79, english: "campaign", japanese: "キャンペーン", pronunciation: "kæmˈpeɪn" },
    { id: 80, english: "cancer", japanese: "がん", pronunciation: "ˈkænsər" },
    { id: 81, english: "candidate", japanese: "候補者", pronunciation: "ˈkændɪdeɪt" },
    { id: 82, english: "capital", japanese: "首都、資本", pronunciation: "ˈkæpɪtəl" },
    { id: 83, english: "captain", japanese: "船長", pronunciation: "ˈkæptən" },
    { id: 84, english: "capture", japanese: "捕らえる", pronunciation: "ˈkæptʃər" },
    { id: 85, english: "carbon", japanese: "炭素", pronunciation: "ˈkɑrbən" },
    { id: 86, english: "career", japanese: "経歴", pronunciation: "kəˈrɪr" },
    { id: 87, english: "careful", japanese: "注意深い", pronunciation: "ˈkerfəl" },
    { id: 88, english: "carry", japanese: "運ぶ", pronunciation: "ˈkæri" },
    { id: 89, english: "category", japanese: "カテゴリー", pronunciation: "ˈkætəgɔri" },
    { id: 90, english: "cause", japanese: "原因", pronunciation: "kɔz" },
    { id: 91, english: "celebrate", japanese: "祝う", pronunciation: "ˈseləbreɪt" },
    { id: 92, english: "center", japanese: "中心", pronunciation: "ˈsentər" },
    { id: 93, english: "central", japanese: "中央の", pronunciation: "ˈsentrəl" },
    { id: 94, english: "century", japanese: "世紀", pronunciation: "ˈsentʃəri" },
    { id: 95, english: "certain", japanese: "確実な", pronunciation: "ˈsɜrtən" },
    { id: 96, english: "challenge", japanese: "挑戦", pronunciation: "ˈtʃæləndʒ" },
    { id: 97, english: "champion", japanese: "チャンピオン", pronunciation: "ˈtʃæmpiən" },
    { id: 98, english: "chance", japanese: "機会", pronunciation: "tʃæns" },
    { id: 99, english: "change", japanese: "変化", pronunciation: "tʃeɪndʒ" },
    { id: 100, english: "character", japanese: "性格、文字", pronunciation: "ˈkærəktər" },
    
    // Words 101-150
    { id: 101, english: "charge", japanese: "料金、担当", pronunciation: "tʃɑrdʒ" },
    { id: 102, english: "chemical", japanese: "化学の", pronunciation: "ˈkemɪkəl" },
    { id: 103, english: "choice", japanese: "選択", pronunciation: "tʃɔɪs" },
    { id: 104, english: "choose", japanese: "選ぶ", pronunciation: "tʃuz" },
    { id: 105, english: "citizen", japanese: "市民", pronunciation: "ˈsɪtəzən" },
    { id: 106, english: "civil", japanese: "市民の", pronunciation: "ˈsɪvəl" },
    { id: 107, english: "claim", japanese: "主張する", pronunciation: "kleɪm" },
    { id: 108, english: "classic", japanese: "古典の", pronunciation: "ˈklæsɪk" },
    { id: 109, english: "climate", japanese: "気候", pronunciation: "ˈklaɪmət" },
    { id: 110, english: "close", japanese: "近い、閉じる", pronunciation: "kloʊs" },
    { id: 111, english: "coach", japanese: "コーチ", pronunciation: "koʊtʃ" },
    { id: 112, english: "coast", japanese: "海岸", pronunciation: "koʊst" },
    { id: 113, english: "collect", japanese: "集める", pronunciation: "kəˈlekt" },
    { id: 114, english: "college", japanese: "大学", pronunciation: "ˈkɑlɪdʒ" },
    { id: 115, english: "combine", japanese: "結合する", pronunciation: "kəmˈbaɪn" },
    { id: 116, english: "comment", japanese: "コメント", pronunciation: "ˈkɑment" },
    { id: 117, english: "common", japanese: "共通の", pronunciation: "ˈkɑmən" },
    { id: 118, english: "community", japanese: "共同体", pronunciation: "kəˈmjunəti" },
    { id: 119, english: "company", japanese: "会社", pronunciation: "ˈkʌmpəni" },
    { id: 120, english: "compare", japanese: "比較する", pronunciation: "kəmˈper" },
    { id: 121, english: "compete", japanese: "競争する", pronunciation: "kəmˈpit" },
    { id: 122, english: "complete", japanese: "完全な", pronunciation: "kəmˈplit" },
    { id: 123, english: "complex", japanese: "複雑な", pronunciation: "kəmˈpleks" },
    { id: 124, english: "computer", japanese: "コンピューター", pronunciation: "kəmˈpjutər" },
    { id: 125, english: "concept", japanese: "概念", pronunciation: "ˈkɑnsept" },
    { id: 126, english: "concern", japanese: "心配", pronunciation: "kənˈsɜrn" },
    { id: 127, english: "condition", japanese: "状態", pronunciation: "kənˈdɪʃən" },
    { id: 128, english: "conduct", japanese: "行う", pronunciation: "kənˈdʌkt" },
    { id: 129, english: "conference", japanese: "会議", pronunciation: "ˈkɑnfərəns" },
    { id: 130, english: "confirm", japanese: "確認する", pronunciation: "kənˈfɜrm" },
    { id: 131, english: "conflict", japanese: "対立", pronunciation: "ˈkɑnflɪkt" },
    { id: 132, english: "connect", japanese: "接続する", pronunciation: "kəˈnekt" },
    { id: 133, english: "consider", japanese: "考慮する", pronunciation: "kənˈsɪdər" },
    { id: 134, english: "constant", japanese: "一定の", pronunciation: "ˈkɑnstənt" },
    { id: 135, english: "contain", japanese: "含む", pronunciation: "kənˈteɪn" },
    { id: 136, english: "content", japanese: "内容", pronunciation: "ˈkɑntent" },
    { id: 137, english: "contest", japanese: "コンテスト", pronunciation: "ˈkɑntest" },
    { id: 138, english: "continue", japanese: "続ける", pronunciation: "kənˈtɪnju" },
    { id: 139, english: "control", japanese: "制御", pronunciation: "kənˈtroʊl" },
    { id: 140, english: "convince", japanese: "説得する", pronunciation: "kənˈvɪns" },
    { id: 141, english: "corner", japanese: "角", pronunciation: "ˈkɔrnər" },
    { id: 142, english: "correct", japanese: "正しい", pronunciation: "kəˈrekt" },
    { id: 143, english: "council", japanese: "議会", pronunciation: "ˈkaʊnsəl" },
    { id: 144, english: "counter", japanese: "カウンター", pronunciation: "ˈkaʊntər" },
    { id: 145, english: "country", japanese: "国", pronunciation: "ˈkʌntri" },
    { id: 146, english: "couple", japanese: "カップル", pronunciation: "ˈkʌpəl" },
    { id: 147, english: "course", japanese: "コース", pronunciation: "kɔrs" },
    { id: 148, english: "cover", japanese: "覆う", pronunciation: "ˈkʌvər" },
    { id: 149, english: "create", japanese: "創造する", pronunciation: "kriˈeɪt" },
    { id: 150, english: "crime", japanese: "犯罪", pronunciation: "kraɪm" },
    
    // Words 151-200
    { id: 151, english: "crisis", japanese: "危機", pronunciation: "ˈkraɪsəs" },
    { id: 152, english: "critical", japanese: "重要な", pronunciation: "ˈkrɪtɪkəl" },
    { id: 153, english: "culture", japanese: "文化", pronunciation: "ˈkʌltʃər" },
    { id: 154, english: "current", japanese: "現在の", pronunciation: "ˈkɜrənt" },
    { id: 155, english: "customer", japanese: "顧客", pronunciation: "ˈkʌstəmər" },
    { id: 156, english: "damage", japanese: "損害", pronunciation: "ˈdæmɪdʒ" },
    { id: 157, english: "danger", japanese: "危険", pronunciation: "ˈdeɪndʒər" },
    { id: 158, english: "database", japanese: "データベース", pronunciation: "ˈdeɪtəbeɪs" },
    { id: 159, english: "daughter", japanese: "娘", pronunciation: "ˈdɔtər" },
    { id: 160, english: "debate", japanese: "議論", pronunciation: "dɪˈbeɪt" },
    { id: 161, english: "decade", japanese: "10年", pronunciation: "ˈdekeɪd" },
    { id: 162, english: "decide", japanese: "決める", pronunciation: "dɪˈsaɪd" },
    { id: 163, english: "decision", japanese: "決定", pronunciation: "dɪˈsɪʒən" },
    { id: 164, english: "declare", japanese: "宣言する", pronunciation: "dɪˈkler" },
    { id: 165, english: "defend", japanese: "守る", pronunciation: "dɪˈfend" },
    { id: 166, english: "define", japanese: "定義する", pronunciation: "dɪˈfaɪn" },
    { id: 167, english: "degree", japanese: "度、学位", pronunciation: "dɪˈgri" },
    { id: 168, english: "deliver", japanese: "届ける", pronunciation: "dɪˈlɪvər" },
    { id: 169, english: "demand", japanese: "要求", pronunciation: "dɪˈmænd" },
    { id: 170, english: "democracy", japanese: "民主主義", pronunciation: "dɪˈmɑkrəsi" },
    { id: 171, english: "depend", japanese: "依存する", pronunciation: "dɪˈpend" },
    { id: 172, english: "describe", japanese: "描写する", pronunciation: "dɪˈskraɪb" },
    { id: 173, english: "design", japanese: "設計", pronunciation: "dɪˈzaɪn" },
    { id: 174, english: "detail", japanese: "詳細", pronunciation: "ˈditeɪl" },
    { id: 175, english: "develop", japanese: "発展させる", pronunciation: "dɪˈveləp" },
    { id: 176, english: "device", japanese: "装置", pronunciation: "dɪˈvaɪs" },
    { id: 177, english: "digital", japanese: "デジタルの", pronunciation: "ˈdɪdʒətəl" },
    { id: 178, english: "direct", japanese: "直接の", pronunciation: "dəˈrekt" },
    { id: 179, english: "director", japanese: "監督", pronunciation: "dəˈrektər" },
    { id: 180, english: "discover", japanese: "発見する", pronunciation: "dɪˈskʌvər" },
    { id: 181, english: "discuss", japanese: "議論する", pronunciation: "dɪˈskʌs" },
    { id: 182, english: "disease", japanese: "病気", pronunciation: "dɪˈziz" },
    { id: 183, english: "display", japanese: "表示する", pronunciation: "dɪˈspleɪ" },
    { id: 184, english: "distance", japanese: "距離", pronunciation: "ˈdɪstəns" },
    { id: 185, english: "document", japanese: "文書", pronunciation: "ˈdɑkjəmənt" },
    { id: 186, english: "domestic", japanese: "国内の", pronunciation: "dəˈmestɪk" },
    { id: 187, english: "doubt", japanese: "疑い", pronunciation: "daʊt" },
    { id: 188, english: "download", japanese: "ダウンロード", pronunciation: "ˈdaʊnloʊd" },
    { id: 189, english: "drama", japanese: "ドラマ", pronunciation: "ˈdrɑmə" },
    { id: 190, english: "dream", japanese: "夢", pronunciation: "drim" },
    { id: 191, english: "driver", japanese: "運転手", pronunciation: "ˈdraɪvər" },
    { id: 192, english: "during", japanese: "〜の間", pronunciation: "ˈdʊrɪŋ" },
    { id: 193, english: "economy", japanese: "経済", pronunciation: "ɪˈkɑnəmi" },
    { id: 194, english: "editor", japanese: "編集者", pronunciation: "ˈedətər" },
    { id: 195, english: "education", japanese: "教育", pronunciation: "ˌedʒəˈkeɪʃən" },
    { id: 196, english: "effect", japanese: "効果", pronunciation: "ɪˈfekt" },
    { id: 197, english: "effort", japanese: "努力", pronunciation: "ˈefərt" },
    { id: 198, english: "election", japanese: "選挙", pronunciation: "ɪˈlekʃən" },
    { id: 199, english: "electric", japanese: "電気の", pronunciation: "ɪˈlektrɪk" },
    { id: 200, english: "element", japanese: "要素", pronunciation: "ˈeləmənt" }
];

// 便利な検索関数
function getWordsByRange(start, end) {
    return vocabularyData.filter(word => word.id >= start && word.id <= end);
}

function getWordById(id) {
    return vocabularyData.find(word => word.id === id);
}

function getTotalWordCount() {
    return vocabularyData.length;
}